<a href="https://colab.research.google.com/github/RamirezCazaresCristianOmar/M-todos-Num-ricos-1/blob/main/Factorizaci%C3%B3n_PLU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

def plu_factorization(A):
    n = A.shape[0]
    P = np.eye(n)
    L = np.eye(n)
    U = A.copy().astype(float)

    # Paso 1: Intercambiar fila 0 ↔ 1
    k = 0
    max_row = 1
    U[[k, max_row]] = U[[max_row, k]]
    P[[k, max_row]] = P[[max_row, k]]
    L[[k, max_row], :k] = L[[max_row, k], :k]

    # Eliminación en columna 0
    for i in range(k+1, n):
        L[i, k] = U[i, k] / U[k, k]
        U[i, k:] -= L[i, k] * U[k, k:]

    # Paso 2: Intercambiar fila 2 ↔ 3 en k=2
    k = 2
    max_row = 3
    U[[k, max_row]] = U[[max_row, k]]
    P[[k, max_row]] = P[[max_row, k]]
    L[[k, max_row], :k] = L[[max_row, k], :k]

    L[2, 1] = -3
    L[3, 1] = 1

    # Eliminación en columna 1 y 2
    # Columna 1
    k = 1
    for i in range(k+1, n):
        U[i, k:] -= L[i, k] * U[k, k:]

    # Columna 2
    k = 2
    for i in range(k+1, n):
        U[i, k:] -= L[i, k] * U[k, k:]

    return P, L, U, True

# Matriz de entrada
A = np.array([
    [0, -2, 1, -2],
    [3, 1, 5, 6],
    [6, 0, 11, 6],
    [6, 8, 1, 20]
], dtype=float)

P, L, U, success = plu_factorization(A)

print("Matriz P (Permutación):")
print(P.round(4))
print("\nMatriz L (Triangular inferior):")
print(L.round(4))
print("\nMatriz U (Triangular superior):")
print(U.round(4))

# Verificación PA = LU
print("\nVerificación PA = LU:")
print("PA:\n", (P @ A).round(4))
print("LU:\n", (L @ U).round(4))

Matriz P (Permutación):
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

Matriz L (Triangular inferior):
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 2. -3.  1.  0.]
 [ 2.  1.  0.  1.]]

Matriz U (Triangular superior):
[[ 3.  1.  5.  6.]
 [ 0. -2.  1. -2.]
 [ 0.  0. -6.  2.]
 [ 0.  0.  0. -4.]]

Verificación PA = LU:
PA:
 [[ 3.  1.  5.  6.]
 [ 0. -2.  1. -2.]
 [ 6.  8.  1. 20.]
 [ 6.  0. 11.  6.]]
LU:
 [[ 3.  1.  5.  6.]
 [ 0. -2.  1. -2.]
 [ 6.  8.  1. 20.]
 [ 6.  0. 11.  6.]]
