<a href="https://colab.research.google.com/github/RamirezCazaresCristianOmar/M-todos-Num-ricos-1/blob/main/Factorizaci%C3%B3n_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:

def lu_factorization(A):
    """
    Implementa la factorización LU de una matriz A.

    Args:
        A (numpy.ndarray): Matriz cuadrada de dimensión n x n

    Returns:
        L (numpy.ndarray): Matriz triangular inferior
        U (numpy.ndarray): Matriz triangular superior
        success (bool): True si la factorización fue exitosa, False si es imposible
    """
    n = len(A)
    # Inicializamos L y U como matrices de ceros
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    # Paso 1: Inicializamos la diagonal de L con 1's
    for i in range(n):
        L[i][i] = 1

    # Copiamos A para no modificar la original
    A = np.array(A, dtype=float)

    # Paso 1: Verificar primer elemento
    if A[0][0] == 0:
        return None, None, False

    # Paso 2: Primera fila de U y primera columna de L
    U[0] = A[0]
    for i in range(1, n):
        L[i][0] = A[i][0] / U[0][0]

    # Pasos 3-5: Procesamiento principal
    for i in range(1, n):
        # Paso 4: Diagonal de U
        suma = sum(L[i][k] * U[k][i] for k in range(i))
        U[i][i] = A[i][i] - suma

        if U[i][i] == 0:  # Verificar si la factorización es posible
            return None, None, False

        # Paso 5: i-ésima fila de U y columna de L
        for j in range(i+1, n):
            # Cálculo de U[i][j]
            suma_u = sum(L[i][k] * U[k][j] for k in range(i))
            U[i][j] = A[i][j] - suma_u

            # Cálculo de L[j][i]
            suma_l = sum(L[j][k] * U[k][i] for k in range(i))
            L[j][i] = (A[j][i] - suma_l) / U[i][i]

    return L, U, True

def solve_lu_system(L, U, b):
    """
    Resuelve el sistema LUx = b usando sustitución hacia adelante y hacia atrás.

    Args:
        L (numpy.ndarray): Matriz triangular inferior
        U (numpy.ndarray): Matriz triangular superior
        b (numpy.ndarray): Vector de términos independientes

    Returns:
        x (numpy.ndarray): Solución del sistema
    """
    n = len(b)
    # Paso 1: Resolver Ly = b (sustitución hacia adelante)
    y = np.zeros(n)
    y[0] = b[0] / L[0][0]
    for i in range(1, n):
        suma = sum(L[i][j] * y[j] for j in range(i))
        y[i] = (b[i] - suma) / L[i][i]

    # Paso 2: Resolver Ux = y (sustitución hacia atrás)
    x = np.zeros(n)
    x[n-1] = y[n-1] / U[n-1][n-1]
    for i in range(n-2, -1, -1):
        suma = sum(U[i][j] * x[j] for j in range(i+1, n))
        x[i] = (y[i] - suma) / U[i][i]

    return x

# Ejemplo de uso con la matriz dada
A = np.array([
    [1, 1, 0, 3],
    [2, 1, -1, 1],
    [3, -1, -1, 2],
    [-1, 2, 3, -1]
], dtype=float)

b = np.array([4, 1, -3, 4], dtype=float)

# Realizar la factorización LU
L, U, success = lu_factorization(A)

if success:
    print("Matriz L:")
    print(np.round(L, 4))
    print("\nMatriz U:")
    print(np.round(U, 4))

    # Resolver el sistema
    x = solve_lu_system(L, U, b)
    print("\nSolución x:")
    print(np.round(x, 4))

    # Verificar la solución
    print("\nVerificación Ax = b:")
    print("Ax =", np.round(np.dot(A, x), 4))
    print("b  =", b)
else:
    print("La factorización LU es imposible para esta matriz.")

Matriz L:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

Matriz U:
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]

Solución x:
[-1.  2.  0.  1.]

Verificación Ax = b:
Ax = [ 4.  1. -3.  4.]
b  = [ 4.  1. -3.  4.]
