<a href="https://colab.research.google.com/github/RamirezCazaresCristianOmar/M-todos-Num-ricos-1/blob/main/Tutorial_de_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy es una biblioteca de código abierto para el lenguaje de programación Python que se utiliza para:
-Realizar cálculos numéricos eficientes en grandes cantidades de datos.

-Programar en Data Science, ingeniería, matemáticas o ciencia.

-Crear vectores y matrices grandes multidimensionales.

-Operar con matrices y vectores de grandes dimensiones.

-Invocar métodos de forma vectorizada.

#Estas son algunas utilidades y funciones basicas que tiene la libreria numpy:

#1.-Importar la libreria numpy.
Esta linea importa la libreria NumPy y la asigna al alias np.Esto permite usar las funciones de NumPy con el prefijo np. para facilitar las escritura del codigo.

In [1]:
import numpy as np

#2.-Creacion de Arrays.
Los arrays NumPy son mas eficientes para realizar calculos numericos que las listas de Python.

In [35]:
#Crear un array unidimensional
array1D = np.array([1, 2, 3, 4, 5])
print("array1D:", array1D)

array1D: [1 2 3 4 5]


In [36]:
#Crear un array multidimensional
array1D = np.array([[1, 2, 3], [4, 5, 6]])
print("array1D:", array1D)


array1D: [[1 2 3]
 [4 5 6]]


In [25]:
#Crear arrays de ceros y unos
array_zeros = np.zeros((2, 3))  # Array de ceros de 2x3
array_ones = np.ones((2, 3))    # Array de unos de 2x3
print("array_zeros:", array_zeros)
print("array_ones:", array_ones)

array_zeros: [[0. 0. 0.]
 [0. 0. 0.]]
array_ones: [[1. 1. 1.]
 [1. 1. 1.]]


#3.-Operaciones Basicas(suma,resta,multiplicacion,division).
Estas operaciones se realizan elemento a elemento entre dos arrays del mismo tamaño.NumPy optimiza estas operaciones para que sean mucho mas rapidas que hacerlas con bucles en Python.


In [5]:
#Crear dos arrays de ejemplo
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [18]:
#Suma
suma = a + b
print("Suma:", suma)

Suma: [5 7 9]


In [19]:
#resta
resta = a - b
print("Resta:", resta)

Resta: [-3 -3 -3]


In [20]:
#multiplicacion
multiplicacion = a * b
print("Multiplicación:", multiplicacion)

Multiplicación: [ 4 10 18]


In [21]:
#division
division = a / b
print("División:", division)

División: [0.25 0.4  0.5 ]


#4.-Crear un Rango de valores.
Crear un array con un rango de numeros,con un paso especificado.Es una forma eficiente de generar secuencias numericas.

In [26]:
rango = np.arange(0, 10, 2)  # Rango de 0 a 10 con paso 2
print("rango:", rango)

rango: [0 2 4 6 8]


#5.-Calcular el producto punto.
Calcula el producto punto(o producto escalar)de dos arrays.Esencial para muchos calculos matematicos y de algebra lineal.

In [34]:
producto_punto = np.dot(array1D, array1D)  # Producto punto de array1D consigo mismo
print("producto_punto:", producto_punto)

producto_punto: 55


#6.-Funciones utiles.


Devuelve la forma(dimensiones)del array como una tupla(numero de filas,numero de columnas)esencial para saber el tamaño del array.

In [37]:
#Obtener la forma del array
forma_array1D = array1D.shape
print("forma_array1D:", forma_array1D)

forma_array1D: (2, 3)


Devuelve el numero total de elementos en el array.Util para iteraciones o para hacer calculos que dependen del tamaño de los datos.

In [38]:
#Obtener el tamaño del array
tamano_array1D = array1D.size
print("tamano_array1D:", tamano_array1D)

tamano_array1D: 6


Devuelve el tipo de datos de los elementos (ejemplo:int64,float64).Importante para entender el tipo de datos con el que estas trabajando y para evitar errores.

In [39]:
#Obtener tipos de datos
tipo_dato_array1D = array1D.dtype
print("tipo_dato_array1D:", tipo_dato_array1D)

tipo_dato_array1D: int64


Devuelve la transpuesta de la matriz.La transpuesta intercambia filas por columnas.Fundamental en algebra lineal.

In [40]:
#Transponer un array
transpuesta_array1D = array1D.T
print("transpuesta_array1D:", transpuesta_array1D)

transpuesta_array1D: [[1 4]
 [2 5]
 [3 6]]
